### ISSUE TITLE
MCD / Base de données

### ISSUE THREAD

**Issue by atterebf** [Raphix93/2HS2179_militants-pour-la-paix#2]
Concernant le MCD, ajouter svp un export png ou jpg du MCD pour ne pas devoir ouvrir drawio chaque fois

Sinon: dans MLD et BD manque le lien entre membership et organisation. Aussi dans MCD la direction entre Membership vers personne car la personne définit l'identité de la membership: en général, toutes les temporalités ont des fléches qui sortent vers les objets (par convention).

Pour les award, il faut distinguer entre le prix en tant que concept —le prix nobel pour la paix comme instance de la classe 'prix' ou ''qualification sociale' qui pourrait être négative— et l'événement de 'recevoir le prix' qui est une temporalité. Il faut donc deux classes, une pour le prix une pour le recevoir le prix

**Comment by Raphix93** [comment]
C'est fait!
